---
name: "Run tests via docker-compose"
on: [push]
jobs:
  docker:
    runs-on: ubuntu-latest
 
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Checkout
        uses: actions/checkout@v3
  
      - name: Start containers
        run: docker-compose -f "docker-compose.yml" up -d --build
  
      - name: Test
        run: docker-compose run app sh -c "python manage.py wait_for_db && python manage.py test"

      - name: Lint
        run: docker-compose run app sh -c "flake8"
